[versions]
groovy = "2.5.14"
junit = "4.13.1"
spock = "1.3-groovy-2.5"

nexus = "1.0.0"

[libraries]
groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
junit = "junit:junit:4.13.1"
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }

plugins-nexus = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus"}

[bundles]
test-commonLibraries = ["groovy-core", "junit", "spock"]
